image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-card-delivery.jar

build_script:
  - chmod +x gradlew
  - chmod +x driver/chromedriver.exe
  - ./gradlew test -Dselenide.headless=true --info